### ISSUE TITLE
Extend status and outages APIs to secondary data holders

### ISSUE THREAD

**Issue by ShaneDoolanAdatree** [ConsumerDataStandardsAustralia/standards-maintenance#598] opened 2023-06-29 04:57 UTC
# Description
Recent issues with AEMO, specifically metering data, has further highlighted the need for ADRs to have at least some visibility into the state of secondary data holder systems without us having to bother primary data holders.

# Area Affected
Common APIs
- [Get Status](https://consumerdatastandardsaustralia.github.io/standards/#get-status)
- [Get Outages](https://consumerdatastandardsaustralia.github.io/standards/#get-outages)

# Change Proposed
Have secondary data holders implement the same status and outages endpoints as primary data holders.

**Comment by JohnLaird-SA** [comment] 2023-06-29 08:44
This would be incredibly useful! We have had quite a few issues recently that required quite a few resources to investigate internal services to trace what could be the root cause. This proposal could have helped quickly identify the problem was not an isolated issue, or related to secondary data holders either.

**Comment by AGL-CDR** [comment] 2023-07-05 23:42
AGL also supports this change. Keeping up with an external party's status and outage scheduling so we can cross reference against issues and errors being detected through our operational support team is becoming more and more time consuming. This change would align the secondary data holder to the rest of the CDR framework and provide a direct line of sight to all participants.

**Comment by nils-work** [comment] 2024-07-03 03:59
Hi @ShaneDoolanAdatree, @JohnLaird-SA, @AGL-CDR 

Although they are not specified in the Standards, AEMO have provided Status and Outages endpoints. Details are provided in their [Developer Portal](https://developer-portal-prd.aemo.com.au/CDR-Common).

The responses from these are also displayed on the [CDS Product Comparator (demo)](https://consumerdatastandardsaustralia.github.io/product-comparator-demo/), in the `AEMO - STATUS AND OUTAGES` tab.

Do they meet your needs?

**Comment by nils-work** [comment] 2024-07-26 02:21
If there are no further comments, this issue will be closed on 30 August 2024.

**Comment by nils-work** [comment] 2024-09-23 04:06
Closing as resolved. For background details see [#477 - Secondary Data Holder Planned Outages and Status](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/477).
If there are further concerns please raise a new issue.

**Closed by nils-work** 2024-09-23 04:06 UTC
Labels: Energy
