### ISSUE TITLE
Client Authentication improvements for Admin API

### ISSUE THREAD

**Issue by CDR-Register-Stream** [ConsumerDataStandardsAustralia/standards-maintenance#360] opened 2020-12-02 22:19 UTC
# Description
[Issue 139](https://github.com/cdr-register/register/issues/139) has been raised on the CDR Register GitHub and explores the opportunity of simplifying the authentication mechanism used against the Admin APIs.

Currently a bespoke client authentication mechanism is documented in the [CDS](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication) but this [CDR Register issue](https://github.com/cdr-register/register/issues/139) explores the opportunity to conform to the normative approach, using issued access tokens to access the Admin APIs. 

This transition would be optional at first, moving to mandatory in the future.

# Area Affected
[Client Authentication](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication) - CDR Register calling Data Holders and Data Recipients. This section would need to define the options,.

[Authorisation scopes](https://consumerdatastandardsaustralia.github.io/standards/#authorisation-scopes) - A new authorisation scope would be required to be used against the GetMetrics API

# Change Proposed
1. Keep the current  authentication method as defined in the[ CDR Register calling Data Holders and Data Recipients section](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication) and move it to optional
2. Add a new optional client authentication method supporting the receipt of access tokens, consistent with the [Data Recipients calling Data Holders](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication) section
3. Provide a transition plan to move between these authentication methods aligned with the CDR Register design
4. Add a new authorisation scope dedicated to the GetMetrics endpoint

**Comment by Susan-CDR** [comment] 2020-12-11 07:59
Suncorp supports moving to the more standard approaches (Options 2-4) but would like to restate our previous feedback for noting.

The current model where the signed jwt is presented directly to the API required a custom approach for our implementation to manage the authentication, rather than delegating this to the IDP. **Build work has been completed for this.**
Options 2-4 allow for a more "standard" approach but will require a slightly different registration process for the CDR Registry. No specific preferences within these options as the implications are more related to those already live with the metrics endpoint. All would mean additional work is required.

**Comment by commbankoss** [comment] 2021-01-15 00:29
Commonwealth Bank supports moving to a normative standards based client authentication, as per our initial post and comments on register [issue 139](https://github.com/cdr-register/register/issues/139). We also believe the change should anticipate additional scopes and API use cases will be required in the future. Finally, the standards should also make clear the existing method is to be deprecated at a future date.

**Comment by mrum-cuscal** [comment] 2021-01-28 05:25
Cuscal prefers the move back to a more standard implementation. We are about to begin the development of this feature and would hope to see confirmation that option 2 is available for us to implement against from the outset.

**Comment by ryderwj** [comment] 2021-01-29 00:29
While Suncorp has completed build activity against the current standard, being able to move to a more standards based approach (Option 2) in time for our initial delivery is a preferable approach.

**Comment by elo360** [comment] 2021-02-03 00:31
ING supports the adoption of the standard approach (option 2). We have completed the build work, however, option 2 is the preferred option and we would prefer to move to option 2  for our live release.

**Comment by biza-io** [comment] 2021-02-03 01:14
Biza.io supports the proposed change and has proceeded with it's current implementations on the assumption that this change will be actioned in a short period of time prior to onboarding.

**Comment by anzbankau** [comment] 2021-02-11 00:18
We are supportive of moving closer to the standards based mechanisms, and feel that such as a change should be present for the July 2021 release so that new Data Holders can use this approach.

We also appreciate that it is made optional to avoid impacting data holders who have implemented as per the existing design. However note the statement that this will be moving to be mandatory in future. Our preference would be to continue having both options available so that existing implementations are not impacted.

**Comment by Ultradata-project** [comment] 2021-02-12 03:41
We support the proposed change for Option 2 closer to the standards based approach as it will be a better long term solution for our 40 clients taking up the Open Banking solution.  With the upcoming July deadline, our preference is for a quick decision allowing for optional take up by July 2021 and a reasonable time for deprecation of the current solution.

**Comment by CDR-API-Stream** [comment] 2021-03-10 05:38
Thank you to everyone who has expressed feedback so far. Based on this feedback, Option 2 is most supported, where Data Holders can make the determination as to which method of client authentication they support. It has been confirmed in conjunction with the @CDR-Register-Stream that the signed-jwt approach would not be deprecated: the CDR Register will continue support both to provide ongoing flexibility for Data Holders.

The DSB and the @CDR-Register-Stream will work together to draft the proposed changes for consideration. @CDR-Register-Stream will elaborate the Register onboarding requirements and changes. As outlined in the change request, the data standards will consider the inclusion of a specific access scope.

**Comment by CDR-API-Stream** [comment] 2021-03-26 04:38
This change has been staged for review here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/tree/maintenance/360--option-b

Key changes:
* Updated [Client Authentication section](http://ec2-18-224-29-97.us-east-2.compute.amazonaws.com/#client-authentication ) to provide a simplified presentation based on authentication method
* Optionality of client authentication method for Data Holders authenticating the CDR Register
* Updated [Get Metrics endpoint](http://ec2-18-224-29-97.us-east-2.compute.amazonaws.com/#get-metrics) description to include required scope iff the DH is authenticating using private_key_jwt
* Added the new scope and description to the [Authorisation Scopes section](http://ec2-18-224-29-97.us-east-2.compute.amazonaws.com/#authorisation-scopes)

The draft changes can be viewed here: http://ec2-18-224-29-97.us-east-2.compute.amazonaws.com/#client-authentication 

An alternative option focused only on Data Holders authenticating the CDR Register is available here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/tree/maintenance/360--option-a

**Comment by CDR-API-Stream** [comment] 2021-04-07 00:41
Based on discussions with the CDR Register team, this draft change has been updated to accomodate a scope for calling the Metadata Update API when the DH supports private_key_jwt authentication of the CDR Register. 

The draft changes can be viewed here: http://ec2-18-224-29-97.us-east-2.compute.amazonaws.com/#client-authentication
The code change can be reviewed here:  https://github.com/ConsumerDataStandardsAustralia/standards-staging/tree/maintenance/360--option-b

**Comment by CDR-Register-Stream** [comment] 2021-04-15 03:43
Based on enquiries we've received regarding go-live of this feature, the following outlines support that the CTS and RAAP platform will provide:

- CTS does not currently test GetMetrics. Support for GetMetrics and both client authentication mechanisms are expected in May 2021.
- CTS was never intended to provide full coverage, it is expected that Data Holder would test their respective endpoints and ensure that they comply with CDS.
- RAAP will capture client_ids and support both authentication mechanisms for GetMetrics in June 2021

**Comment by commbankoss** [comment] 2021-04-15 07:24
We propose changing the following section from:

```
- Self-signed JWT client assertion authenticated by the protected request endpoint according to Self-signed JWT Client Authentication, or
- private_key_jwt authentication using client_credentials authorisation grant flow according to Private Key JWT Client Authentication.
```

to:

```
- (Preferred) private_key_jwt authentication using client_credentials authorisation grant flow according to Private Key JWT Client Authentication, or
- Self-signed JWT client assertion authenticated by the protected request endpoint according to Self-signed JWT Client Authentication.

Note: private_key_jwt is the recommended authentication option as it is more aligned with normative standards, supported by vendor software. Self-signed JWT may be deprecated in the future.
```

**Comment by perlboy** [comment] 2021-04-15 07:41
@commbankoss Support the proposal but given the use of RFC2119 terms and the fact "prefer" is a singular persons adjective probably best to call this _RECOMMENDED_ or _SHOULD_ which are considered equal without being binding.

**Comment by CDR-API-Stream** [comment] 2021-04-15 23:00
Thanks @commbankoss and @perlboy this has been incorporated. I haven't included the note around deprecation because this is not planned.

Change is staged here: https://github.com/ConsumerDataStandardsAustralia/standards-staging/compare/release/1.8.0...maintenance/360--option-b
The draft changes can be viewed here:  http://ec2-18-224-29-97.us-east-2.compute.amazonaws.com/#client-authentication

**Comment by CDR-API-Stream** [comment] 2021-04-29 23:30
The outcome of this issue has been [approved by the Data Standards Chair](https://github.com/ConsumerDataStandardsAustralia/standards/issues/161#issue-806886083) for inclusion in v1.9.0. A change to the data standards was recommended.

This issue will be closed accordingly.

**Closed by CDR-API-Stream** 2021-04-29 23:30 UTC
Labels: In Backlog, change request
