### ISSUE TITLE
Updates required to a property and the example provided in EnergyPlanSolarFeedInTariff schema

### ISSUE THREAD

**Issue by NeelVerma** [ConsumerDataStandardsAustralia/standards-maintenance#456] opened 2022-01-10 04:07 UTC
# Description
Update required to a property and the provided example in EnergyPlanSolarFeedInTariff schema. 

# Area Affected
- Affected URL > https://consumerdatastandardsaustralia.github.io/standards/#tocSenergyplansolarfeedintariff
- The "Type", "Description" and associated example of the property "timeVaryingTariffs" should mention that it is an array. 
- The provided example shows "timevaryingTariffs" with a "tariffUType" of "singleTariff" which is incorrect as "timevaryingTariffs" is conditional, it is mandatory when the "tariffUType" is set to "timeVaryingTariffs".

# Change Proposed
- Please update the "Type", "Description" and associated example of the property "timeVaryingTariffs" to indicate that it is an array. 
- Please update the "tariffUType" in the given example to "timevaryingTariffs" as "timevaryingTariffs" is conditional, it is mandatory when the "tariffUType" is set to "timeVaryingTariffs". 
- Please refer to the following link with detailed information from @joe-parkin-aer from Australian Energy Regulator (AER) about this object previously, another suggestion would be to use a combined example to cover this scenario as mentioned here --> [https://github.com/ConsumerDataStandardsAustralia/standards/issues/190#issuecomment-927507635]
- Please refer to the attached image with the requested changes highlighted: 
<img width="960" alt="CDS_Change Request for EnergyPlanSolarFeedInTariff_Updates_NV" src="https://user-images.githubusercontent.com/93966326/148717263-6cbbacf4-93c7-4a3e-860e-5d770219caa2.png">

**Comment by mattyp** [comment] 2024-01-29 04:28
+1

This is duplicate of https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/624#issue-2029851589

**Comment by nils-work** [comment] 2024-07-11 07:03
Hi @NeelVerma 
Re: your proposed changes:

> Please update the "Type", "Description" and associated example of the property "timeVaryingTariffs" to indicate that it is an array.

This was resolved in Standards [version 1.30.0](https://consumerdatastandardsaustralia.github.io/standards/#change-log) when [EnergyPlanSolarFeedInTariffV3](https://consumerdatastandardsaustralia.github.io/standards/#cdr-energy-api_schemas_tocSenergyplansolarfeedintariffv3) was introduced.

> Please update the "tariffUType" in the given example to "timevaryingTariffs" as "timevaryingTariffs" is conditional, it is mandatory when the "tariffUType" is set to "timeVaryingTariffs".

The Non-normative example demonstrates the full structure of all properties in the schema.
As both the _singleTariff_ and _timeVaryingTariffs_ fields are conditionally mandatory based on the value of _tariffUType_, `singleTariff` is a valid value and simply demonstrates the first enum option that references that structure.

Please comment if I've misunderstood your concerns or if this issue can now be closed.

I have also noted that there appears to be a [copy/paste error](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/647#issuecomment-2222175955) in the Description of the _tariffUType_ field which can be addressed in Maintenance Iteration 20.

**Comment by nils-work** [comment] 2024-07-26 02:23
If there are no further comments, this issue will be closed on 30 August 2024.

**Closed** 2024-08-30 00:23 UTC
Labels: Energy
