### ISSUE TITLE
Get Energy Account Detail API - Proposed Changes

### ISSUE THREAD

**Issue by agl-cdrprogram** [ConsumerDataStandardsAustralia/standards-maintenance#517] opened 2022-05-30 02:32 UTC
# Description
In the Get Energy API we have identified some areas of concerns that should be addressed and have proposed to the following solutions to enable this to be better suited for Energy Retailers across the board. 

# Area Affected
We have noticed that there can be enhancements added to the fields:
1. timeOfUseRates and demandCharges stored within the  tariffPeriod section. 
2. Updates to the EnergyPlanSolarFeedInTariff for SingleTariff SolarFeedInTariff
3. EnergyPlanControlledLoad / controlledLoad changes. 
4. New enum for 'public holiday' in the timeofuse 'days' field (EnergyPlanTariffPeriod).     

# Change Proposed
We are proposing to enhance these segments by adding additional fields/provisions to allow further detail to be provided, which allows for further context and complete tariff information. 

[GET ENERGY ACCOUNT DETAIL api.docx](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/files/8794983/GET.ENERGY.ACCOUNT.DETAIL.api.docx)

**Comment by agl-cdrprogram** [comment] 2022-06-03 06:49
Please reference this update version of the word doc. 

[CR#517_GET ENERGY ACCOUNT DETAIL api.docx](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/files/8830179/CR.517_GET.ENERGY.ACCOUNT.DETAIL.api.docx)

**Comment by perlboy** [comment] 2022-06-12 06:30
It'd be good if requests can be placed in native format. It helps readers go through things faster and also means GitHub search works better.

> TOU Tariff: Request to add provisions for surfacing below information in the ‘timeOfUse’ segment (of tariffPeriod section in Get energy account detail): 
>   -	 ‘MONTH’ (Start month – End month)’ (e.g., 1 November and 31 March) and/or 
>   -	 ‘SEASON’ (e.g., summer/winter)
>
> Demand Tariff: Request to add provisions for surfacing below information in the ‘demandCharges’ segment (of tariffPeriod section in Get energy account detail): 
>    -	 ‘MONTH’ (Start month – End month)’ (e.g., 1 April to 31 May) and/or 
>   -	 ‘SEASON’ (e.g., summer/winter)

This looks like an overlap with https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/519 but for a different endpoint. `MONTH` makes sense (although start/finish date would be better imo) but I'm dubious about `SEASON`.

> There are specific demand tariffs defined calculated as below: Peak demand applies 4pm -9pm weekdays and weekends all year. A minimum demand of 1.0 KW applies and off peak demand applies all other time.
> Therefore, request to consider above scenario and add/provide provisions for passing multiple start time and end time sections in the ‘demandCharges’ segment (of tariffPeriod segment of Get energy account detail api): 
> In the current payload we can only provide one timestamp

This is incorrect. Many timestamps can be provided by providing many tuples in the array. Will this not work?

> Can we request the current structure of 'EnergyPlanSolarFeedInTariff' (within GET ENERGY ACCOUNT DETAIL) to be updated to support representation of solarFeedInTariff with block rates/stepped rates applicable?

This looks like a duplicate of https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/520 ?

> 3.	The current ‘controlledLoad’ (EnergyPlanControlledLoad) segment within Get Energy Account Detail API, is an object and not an array structure and in this instance only one set of controlled load detail can be passed to the structure.
> However, there can be few instances where a customer has two controlledLoad tariffs applicable say e.g., both Tariff 31 and 33 rates applicable to customer’s account Is it possible to update same or provide feasibility for passing multiple ‘controlledLoad’ tariff details within this segment (as applicable)?

Making this an array will break other components of the payload. What about moving the `period` into the `rates` array within this object instead?

> Request to add enum – ‘Public Holiday’ within the list timeOfUse – ‘days’ field

This looks like a duplicate of https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/502

I'm dubious about Public Holiday being introduced. Public Holiday where?

**Comment by agl-cdrprogram** [comment] 2022-06-20 00:52
> It'd be good if requests can be placed in native format. It helps readers go through things faster and also means GitHub search works better.
> 
> > TOU Tariff: Request to add provisions for surfacing below information in the ‘timeOfUse’ segment (of tariffPeriod section in Get energy account detail):
> > 
> > * ‘MONTH’ (Start month – End month)’ (e.g., 1 November and 31 March) and/or
> > * ‘SEASON’ (e.g., summer/winter)
> > 
> > Demand Tariff: Request to add provisions for surfacing below information in the ‘demandCharges’ segment (of tariffPeriod section in Get energy account detail):
> > 
> > * ‘MONTH’ (Start month – End month)’ (e.g., 1 April to 31 May) and/or
> > * ‘SEASON’ (e.g., summer/winter)
> 
> This looks like an overlap with #519 but for a different endpoint. `MONTH` makes sense (although start/finish date would be better imo) but I'm dubious about `SEASON`.
> 
> > There are specific demand tariffs defined calculated as below: Peak demand applies 4pm -9pm weekdays and weekends all year. A minimum demand of 1.0 KW applies and off peak demand applies all other time.
> > Therefore, request to consider above scenario and add/provide provisions for passing multiple start time and end time sections in the ‘demandCharges’ segment (of tariffPeriod segment of Get energy account detail api):
> > In the current payload we can only provide one timestamp
> 
> This is incorrect. Many timestamps can be provided by providing many tuples in the array. Will this not work?
> 
> > Can we request the current structure of 'EnergyPlanSolarFeedInTariff' (within GET ENERGY ACCOUNT DETAIL) to be updated to support representation of solarFeedInTariff with block rates/stepped rates applicable?
> 
> This looks like a duplicate of #520 ?
> 
> > 3. The current ‘controlledLoad’ (EnergyPlanControlledLoad) segment within Get Energy Account Detail API, is an object and not an array structure and in this instance only one set of controlled load detail can be passed to the structure.
> >    However, there can be few instances where a customer has two controlledLoad tariffs applicable say e.g., both Tariff 31 and 33 rates applicable to customer’s account Is it possible to update same or provide feasibility for passing multiple ‘controlledLoad’ tariff details within this segment (as applicable)?
> 
> Making this an array will break other components of the payload. What about moving the `period` into the `rates` array within this object instead?
> 
> > Request to add enum – ‘Public Holiday’ within the list timeOfUse – ‘days’ field
> 
> This looks like a duplicate of #502
> 
> I'm dubious about Public Holiday being introduced. Public Holiday where?

Happy to omit 'Public holiday' proposal request , however suggested it, as this may be utilised for commercial tariffs and might be a tranche 2 consideration.
As there are few tariffs (state / distributor specific)  where 
-	weekday rates gets applied for Public holiday or
-	weekend rates gets applied for Public holiday,
 
therefore, In order to provide a distinction of for what day the tariff is applied, proposed separate enum as ‘Public holiday’

e.g refer links (pg – 29, 33, 37)- https://www.aer.gov.au/system/files/Powercor%20-%20APP05%20-%20Tariff%20structure%20statement%20reasons%20-%2031%20January%202020.pdf

**Closed** 2022-06-20 01:13 UTC
Labels: change request
